services:
  mariadb:
    image: mariadb:latest
    container_name: todo-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb_data:/var/lib/mysql
    networks:
      - todo-net

  backend:
    build:
      context: .
      dockerfile: todo-backend/Dockerfile
    container_name: todo-backend
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      - MARIADB_CONNECTION=server=mariadb;port=3306;database=todo_app;user=root;password=root
    volumes:
      - ./todo-backend/WebapiTodo/appsettings.json:/app/appsettings.json
    networks:
      - todo-net
      
networks:
  todo-net:
    driver: bridge
