version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: todo-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
